// apps/little-things-svelte/src/lib/components/product/ImageZoom.svelte
<script lang="ts">
import type { ProductImage } from "@commercengine/storefront";
import { X } from "lucide-svelte";
import StorefrontImage from "../StorefrontImage.svelte";

interface Props {
  images: ProductImage[];
  initialIndex: number;
  isOpen: boolean;
  onclose: () => void;
}

let { images, initialIndex, isOpen, onclose }: Props = $props();

let scrollContainer: HTMLDivElement | undefined = $state();

$effect(() => {
  if (!isOpen) return;

  function handleEscKey(event: KeyboardEvent) {
    if (event.key === "Escape") onclose();
  }

  document.addEventListener("keydown", handleEscKey);
  document.body.style.overflow = "hidden";

  return () => {
    document.removeEventListener("keydown", handleEscKey);
    document.body.style.overflow = "unset";
  };
});

$effect(() => {
  if (isOpen && scrollContainer) {
    const el = scrollContainer.children[0]?.children[initialIndex] as HTMLElement | undefined;
    if (el) el.scrollIntoView();
  }
});
</script>

{#if isOpen}
	<div class="fixed inset-0 z-50 bg-black/90 backdrop-blur-sm animate-fade-in">
		<button
			type="button"
			class="absolute inset-0 cursor-pointer border-0 bg-transparent p-0"
			onclick={onclose}
			aria-label="Close image zoom"
		></button>
		<button
			type="button"
			onclick={onclose}
			class="absolute right-6 top-6 z-10 border-none bg-transparent p-2 text-white hover:bg-transparent"
			aria-label="Close"
		>
			<X class="h-8 w-8" />
		</button>
		<div bind:this={scrollContainer} class="relative h-full w-full overflow-y-auto">
			<div class="space-y-4">
				{#each images as image (image.id)}
					<div class="flex w-full justify-center">
						<StorefrontImage
							{image}
							alt={image.alternate_text || 'Product view'}
							variant="zoom"
							width={1200}
							height={1200}
							class="w-full max-w-3xl object-contain"
						/>
					</div>
				{/each}
			</div>
		</div>
	</div>
{/if}

// apps/linea/src/components/product/ImageZoom.tsx
import { X } from "lucide-react";
import type * as React from "react";
import { useEffect, useRef } from "react";
import { Button } from "@/components/ui/button";

interface ImageZoomProps {
  images: string[];
  initialIndex: number;
  isOpen: boolean;
  onClose: () => void;
}

const ImageZoom = ({ images, initialIndex, isOpen, onClose }: ImageZoomProps) => {
  const scrollRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    const handleEscKey = (event: KeyboardEvent) => {
      if (event.key === "Escape") {
        onClose();
      }
    };

    if (isOpen) {
      document.addEventListener("keydown", handleEscKey);
      document.body.style.overflow = "hidden";
    }

    return () => {
      document.removeEventListener("keydown", handleEscKey);
      document.body.style.overflow = "unset";
    };
  }, [isOpen, onClose]);

  // Scroll to the selected image when modal opens
  useEffect(() => {
    if (isOpen && scrollRef.current) {
      const imageElement = scrollRef.current.children[0]?.children[initialIndex] as HTMLElement;
      if (imageElement) {
        imageElement.scrollIntoView();
      }
    }
  }, [isOpen, initialIndex]);

  if (!isOpen) return null;

  const handleBackdropKeyDown = (event: React.KeyboardEvent) => {
    if (event.key === "Enter" || event.key === " ") {
      event.preventDefault();
      onClose();
    }
  };

  return (
    <div className="fixed inset-0 z-50 bg-black/90 backdrop-blur-sm animate-fade-in">
      {/* Backdrop */}
      <button
        type="button"
        className="absolute inset-0 border-0 p-0 cursor-pointer bg-transparent"
        onClick={onClose}
        onKeyDown={handleBackdropKeyDown}
        aria-label="Close image zoom"
      />

      {/* Close button */}
      <Button
        variant="ghost"
        size="sm"
        onClick={onClose}
        className="absolute top-6 right-6 z-10 hover:bg-transparent text-black border-none p-2"
      >
        <X className="h-8 w-8" />
      </Button>

      {/* Scrollable image container */}
      <div ref={scrollRef} className="relative w-full h-full overflow-y-auto">
        <div className="space-y-4">
          {images.map((image) => (
            <div key={image} className="w-full flex justify-center">
              <img
                src={image}
                alt="Product view"
                className="w-full max-w-none object-cover animate-scale-in"
              />
            </div>
          ))}
        </div>
      </div>
    </div>
  );
};

export default ImageZoom;
