// apps/soja-svelte/src/lib/components/product/ProductInfo.svelte
<script lang="ts">
import { formatPrice } from "@ce/soja-ui/lib/format";
import type { Variant, VariantOption } from "@commercengine/storefront";
import { checkout } from "$lib/checkout.svelte";
import { getProductTags, type SojaProductDetail, splitDescription } from "$lib/product-meta";
import { cn } from "$lib/utils";
import { getOptionSelectionValue, getVariantOption } from "$lib/variants";
import { wishlist } from "$lib/wishlist.svelte";
import WishlistButton from "../WishlistButton.svelte";
import QuantityStepper from "./QuantityStepper.svelte";

interface Props {
  product: SojaProductDetail;
  selectedVariantId: string | null;
  selectedOptions: Record<string, string>;
  allOptionsSelected: boolean;
  onoptionchange: (optionKey: string, optionValue: string) => void;
  tagLimit?: number;
}

let {
  product,
  selectedVariantId,
  selectedOptions,
  allOptionsSelected,
  onoptionchange,
  tagLimit = 6,
}: Props = $props();

let adding = $state(false);
let quantity = $state(1);

/** Backorder counts as purchasable: it sells now and ships when restocked. */
function isPurchasableStock(entity: { stock_available: boolean; backorder?: boolean }): boolean {
  return entity.stock_available || Boolean(entity.backorder);
}

function isColorValue(value: unknown): value is { name: string; hexcode: string } {
  if (typeof value !== "object" || value === null) return false;
  const maybe = value as { name?: unknown; hexcode?: unknown };
  return typeof maybe.name === "string" && typeof maybe.hexcode === "string";
}

function optionValues(option: VariantOption) {
  const values: Array<{ selectionValue: string; label: string; hexcode?: string }> = [];
  const seen = new Set<string>();

  if (option.type === "color") {
    for (const raw of option.value) {
      if (!isColorValue(raw) || seen.has(raw.name)) continue;
      seen.add(raw.name);
      values.push({ selectionValue: raw.name, label: raw.name, hexcode: raw.hexcode });
    }
    return values;
  }

  for (const raw of option.value) {
    if (typeof raw !== "string" || seen.has(raw)) continue;
    seen.add(raw);
    values.push({ selectionValue: raw, label: raw });
  }
  return values;
}

const variants = $derived(product.variants ?? []);
const selectedVariant = $derived(
  product.has_variant ? (variants.find((v) => v.id === selectedVariantId) ?? null) : null
);

const optionGroups = $derived.by(() => {
  const variantOptions = product.has_variant ? (product.variant_options ?? []) : [];
  if (variantOptions.length === 0) return [];

  const baseSelection: Record<string, string> = {};
  for (const option of variantOptions) {
    const value = selectedOptions[option.key];
    if (value) baseSelection[option.key] = value;
  }

  const matches = (variant: Variant, selection: Record<string, string>) =>
    Object.entries(selection).every(([key, expected]) => {
      const option = getVariantOption(variant, key);
      return option ? getOptionSelectionValue(option) === expected : false;
    });

  return variantOptions.map((option) => ({
    option,
    values: optionValues(option).map((value) => ({
      ...value,
      isPurchasable: variants.some(
        (variant) =>
          matches(variant, { ...baseSelection, [option.key]: value.selectionValue }) &&
          isPurchasableStock(variant)
      ),
    })),
  }));
});

const price = $derived(selectedVariant?.pricing?.selling_price ?? product.pricing.selling_price);
const currency = $derived(selectedVariant?.pricing?.currency ?? product.pricing.currency);
const compareAt = $derived(selectedVariant?.pricing?.listing_price ?? product.pricing.listing_price);
const onSale = $derived(typeof compareAt === "number" && compareAt > price);

const stockSource = $derived(product.has_variant ? selectedVariant : product);
const hasCompleteSelection = $derived(
  !product.has_variant || (allOptionsSelected && Boolean(selectedVariant))
);
const inStock = $derived(stockSource ? isPurchasableStock(stockSource) : false);
const isBackorder = $derived(
  Boolean(stockSource && !stockSource.stock_available && stockSource.backorder)
);
const canAddToCart = $derived(hasCompleteSelection && inStock && !adding);

const tagline = $derived(
  selectedVariant?.short_description ||
    product.short_description ||
    splitDescription(product.description).lede
);
const tags = $derived(getProductTags(product.tags, tagLimit));
const sku = $derived(selectedVariant?.sku ?? product.sku);
const wishlisted = $derived(wishlist.isInWishlist(product.id, selectedVariantId));

const ctaLabel = $derived(
  !hasCompleteSelection
    ? "Select an option"
    : !inStock
      ? "Out of stock"
      : adding
        ? "Adding…"
        : "Add to Cart"
);

async function addToCart() {
  if (!canAddToCart) return;
  adding = true;
  try {
    await checkout.addToCart(product.id, selectedVariantId, quantity);
  } finally {
    adding = false;
  }
}
</script>

<div class="flex flex-col gap-10">
	<div class="flex flex-col gap-5">
		<h1 class="font-display text-[2rem] tracking-display tablet:text-display">{product.name}</h1>

		{#if selectedVariant && selectedVariant.name !== product.name}
			<p class="text-meta text-muted-foreground">{selectedVariant.name}</p>
		{/if}

		{#if tagline}
			<p class="max-w-[460px] text-meta leading-relaxed whitespace-pre-line text-foreground/75">
				{tagline}
			</p>
		{/if}

		<div class="flex items-baseline gap-3">
			<p class="font-display text-title tracking-display">{formatPrice(price, currency)}</p>
			{#if onSale}
				<p class="text-meta text-muted-foreground line-through">
					{formatPrice(compareAt, currency)}
				</p>
			{/if}
		</div>
	</div>

	{#if tags.length > 0}
		<div class="flex flex-wrap gap-x-6 gap-y-2 text-meta text-muted-foreground">
			{#each tags as tag (tag)}
				<span class="capitalize">{tag}</span>
			{/each}
		</div>
	{/if}

	{#each optionGroups as group (group.option.key)}
		<fieldset class="flex flex-col gap-4">
			<legend class="text-meta text-muted-foreground">
				Select {group.option.name || group.option.key}
			</legend>
			<div class="flex flex-wrap gap-2">
				{#each group.values as value (value.selectionValue)}
					<button
						type="button"
						onclick={() => onoptionchange(group.option.key, value.selectionValue)}
						disabled={!value.isPurchasable}
						aria-pressed={selectedOptions[group.option.key] === value.selectionValue}
						class={cn(
							"flex h-11 items-center gap-2 border px-5 text-meta transition-colors duration-300 ease-soja",
							selectedOptions[group.option.key] === value.selectionValue
								? "border-foreground bg-foreground text-background"
								: "border-border hover:border-foreground",
							!value.isPurchasable &&
								"pointer-events-none text-muted-foreground line-through opacity-40"
						)}
					>
						{#if value.hexcode}
							<span
								aria-hidden="true"
								class="h-3 w-3 border border-black/10"
								style={`background-color:${value.hexcode}`}
							></span>
						{/if}
						{value.label}
					</button>
				{/each}
			</div>
		</fieldset>
	{/each}

	<div class="flex flex-col gap-5">
		{#if hasCompleteSelection || sku}
			<p class="flex flex-wrap gap-x-3 text-meta text-muted-foreground">
				{#if hasCompleteSelection}
					<span>{inStock ? (isBackorder ? "Made to order" : "In stock") : "Out of stock"}</span>
				{/if}
				{#if sku}
					<span>SKU {sku}</span>
				{/if}
			</p>
		{/if}

		<div class="flex flex-wrap items-center gap-3">
			<QuantityStepper value={quantity} onchange={(next) => (quantity = next)} />
			<button
				type="button"
				onclick={addToCart}
				disabled={!canAddToCart}
				class="h-12 flex-1 min-w-[200px] bg-primary px-8 text-meta text-primary-foreground transition-colors duration-300 ease-soja hover:bg-primary-hover disabled:pointer-events-none disabled:opacity-40"
			>
				{ctaLabel}
			</button>
			<WishlistButton
				active={wishlisted}
				onclick={() => wishlist.toggleWishlist(product.id, selectedVariantId)}
				variant="control"
			/>
		</div>
	</div>
</div>

// apps/linea/src/components/product/ProductInfo.tsx
import { useCheckout } from "@commercengine/checkout/react";
import type { Product, VariantOption } from "@commercengine/storefront";
import { Heart, Minus, Plus } from "lucide-react";
import { useMemo, useState } from "react";
import { Link } from "react-router-dom";
import {
  Breadcrumb,
  BreadcrumbItem,
  BreadcrumbLink,
  BreadcrumbList,
  BreadcrumbPage,
  BreadcrumbSeparator,
} from "@/components/ui/breadcrumb";
import { Button } from "@/components/ui/button";
import { formatPrice } from "@/lib/format";
import { getOptionSelectionValue, getVariantOption } from "@/lib/variants";
import { useWishlist } from "@/lib/wishlist";

interface ProductInfoProps {
  product: Product;
  selectedVariantId: string | null;
  selectedOptions: Record<string, string>;
  allOptionsSelected: boolean;
  onOptionChange: (optionKey: string, optionValue: string) => void;
}

type OptionGroup = {
  option: VariantOption;
  values: Array<{
    selectionValue: string;
    label: string;
    hexcode?: string;
    isPurchasable: boolean;
  }>;
};

const isVariantPurchasable = (variant: Product["variants"][number]): boolean => {
  return variant.stock_available || Boolean(variant.backorder);
};

const isColorVariantOptionValue = (
  value: unknown
): value is {
  name: string;
  hexcode: string;
} => {
  if (typeof value !== "object" || value === null) return false;

  const maybeColor = value as { name?: unknown; hexcode?: unknown };
  return typeof maybeColor.name === "string" && typeof maybeColor.hexcode === "string";
};

const getVariantOptionValues = (
  option: VariantOption
): Array<{
  selectionValue: string;
  label: string;
  hexcode?: string;
}> => {
  const values: Array<{
    selectionValue: string;
    label: string;
    hexcode?: string;
  }> = [];
  const seen = new Set<string>();

  if (option.type === "color") {
    for (const rawValue of option.value) {
      if (!isColorVariantOptionValue(rawValue)) continue;
      const selectionValue = rawValue.name;
      if (seen.has(selectionValue)) continue;

      seen.add(selectionValue);
      values.push({
        selectionValue,
        label: rawValue.name,
        hexcode: rawValue.hexcode,
      });
    }
    return values;
  }

  for (const rawValue of option.value) {
    if (typeof rawValue !== "string") continue;
    if (seen.has(rawValue)) continue;

    seen.add(rawValue);
    values.push({
      selectionValue: rawValue,
      label: rawValue,
    });
  }

  return values;
};

const ProductInfo = ({
  product,
  selectedVariantId,
  selectedOptions,
  allOptionsSelected,
  onOptionChange,
}: ProductInfoProps) => {
  const { addToCart } = useCheckout();
  const { isInWishlist, toggleWishlist } = useWishlist();
  const [quantity, setQuantity] = useState(1);
  const [adding, setAdding] = useState(false);
  const wishlisted = isInWishlist(product.id, selectedVariantId);

  const selectedVariant = product.has_variant
    ? product.variants.find((v) => v.id === selectedVariantId)
    : null;

  const optionGroups = useMemo(() => {
    if (!product.has_variant || !product.variant_options) return [];

    const optionKeys = product.variant_options.map((option) => option.key);
    const baseSelection = optionKeys.reduce<Record<string, string>>((acc, key) => {
      const value = selectedOptions[key];
      if (value) acc[key] = value;
      return acc;
    }, {});

    const matchesSelection = (
      variant: Product["variants"][number],
      selection: Record<string, string>
    ) => {
      return Object.entries(selection).every(([key, expectedValue]) => {
        const option = getVariantOption(variant, key);
        return option ? getOptionSelectionValue(option) === expectedValue : false;
      });
    };

    const groups: OptionGroup[] = product.variant_options.map((option) => {
      const resolvedValues = getVariantOptionValues(option).map((optionValue) => {
        const candidateSelection = {
          ...baseSelection,
          [option.key]: optionValue.selectionValue,
        };
        const isPurchasable = product.variants.some((variant) => {
          return matchesSelection(variant, candidateSelection) && isVariantPurchasable(variant);
        });

        return {
          selectionValue: optionValue.selectionValue,
          label: optionValue.label,
          hexcode: optionValue.hexcode,
          isPurchasable,
        };
      });

      return {
        option,
        values: resolvedValues,
      };
    });

    return groups;
  }, [product, selectedOptions]);

  const displayPrice = selectedVariant?.pricing?.selling_price ?? product.pricing.selling_price;
  const displayCurrency = selectedVariant?.pricing?.currency ?? product.pricing.currency;
  const hasCompleteVariantSelection =
    !product.has_variant || (allOptionsSelected && !!selectedVariant);
  const isPurchasable = product.has_variant
    ? selectedVariant
      ? isVariantPurchasable(selectedVariant)
      : false
    : product.stock_available || Boolean(product.backorder);
  const canAddToCart = hasCompleteVariantSelection && isPurchasable && !adding;

  const categoryName = product.categories?.[0]?.name;
  const categorySlug = product.categories?.[0]?.slug;

  const incrementQuantity = () => setQuantity((prev) => prev + 1);
  const decrementQuantity = () => setQuantity((prev) => Math.max(1, prev - 1));

  const handleAddToCart = async () => {
    if (product.has_variant && !selectedVariantId) return;

    setAdding(true);
    try {
      await addToCart(product.id, selectedVariantId, quantity);
    } finally {
      setAdding(false);
    }
  };

  return (
    <div className="space-y-6">
      {/* Breadcrumb - Show only on desktop */}
      <div className="hidden lg:block">
        <Breadcrumb>
          <BreadcrumbList>
            <BreadcrumbItem>
              <BreadcrumbLink asChild>
                <Link to="/">Home</Link>
              </BreadcrumbLink>
            </BreadcrumbItem>
            {categoryName && (
              <>
                <BreadcrumbSeparator />
                <BreadcrumbItem>
                  <BreadcrumbLink asChild>
                    <Link to={`/category/${categorySlug}`}>{categoryName}</Link>
                  </BreadcrumbLink>
                </BreadcrumbItem>
              </>
            )}
            <BreadcrumbSeparator />
            <BreadcrumbItem>
              <BreadcrumbPage>{product.name}</BreadcrumbPage>
            </BreadcrumbItem>
          </BreadcrumbList>
        </Breadcrumb>
      </div>

      {/* Product title and price */}
      <div className="space-y-2">
        <div className="flex justify-between items-start">
          <div>
            {categoryName && (
              <p className="text-sm font-light text-muted-foreground mb-1">{categoryName}</p>
            )}
            <h1 className="text-2xl md:text-3xl font-light text-foreground">{product.name}</h1>
          </div>
          <div className="text-right">
            <p className="text-xl font-light text-foreground">
              {formatPrice(displayPrice, displayCurrency)}
            </p>
          </div>
        </div>
      </div>

      {/* Variant selector */}
      {product.has_variant && product.variant_options && (
        <div className="space-y-4 py-4 border-b border-border">
          {optionGroups.map(({ option, values }) => (
            <div key={option.key} className="space-y-2">
              <h3 className="text-sm font-light text-foreground capitalize">{option.name}</h3>
              <div className="flex flex-wrap gap-2">
                {values.map(({ selectionValue, label, hexcode, isPurchasable }) => {
                  const isColor = option.type === "color";
                  const isSelected = selectedOptions[option.key] === selectionValue;

                  return (
                    <button
                      key={`${option.key}-${selectionValue}`}
                      type="button"
                      onClick={() => onOptionChange(option.key, selectionValue)}
                      aria-disabled={!isPurchasable}
                      disabled={!isPurchasable}
                      title={label}
                      className={`text-sm font-light border transition-colors ${
                        isColor ? "size-9 rounded-full p-0.5" : "px-4 py-2"
                      } ${
                        isSelected ? "border-foreground" : "border-border hover:border-foreground"
                      } ${!isPurchasable ? "opacity-50 cursor-not-allowed" : ""}`}
                    >
                      {isColor ? (
                        <span
                          className="block size-full rounded-full"
                          style={{ backgroundColor: hexcode }}
                        />
                      ) : (
                        label
                      )}
                    </button>
                  );
                })}
              </div>
            </div>
          ))}
        </div>
      )}

      {/* Product attributes */}
      {product.attributes.length > 0 && (
        <div className="space-y-4 py-4 border-b border-border">
          {product.attributes.map((attr) => (
            <div key={attr.key} className="space-y-2">
              <h3 className="text-sm font-light text-foreground capitalize">{attr.name}</h3>
              <p className="text-sm font-light text-muted-foreground">{String(attr.value)}</p>
            </div>
          ))}
        </div>
      )}

      {/* Quantity and Add to Cart */}
      <div className="space-y-4">
        <div className="flex items-center gap-4">
          <span className="text-sm font-light text-foreground">Quantity</span>
          <div className="flex items-center border border-border">
            <Button
              variant="ghost"
              size="sm"
              onClick={decrementQuantity}
              className="h-10 w-10 p-0 hover:bg-transparent hover:opacity-50 rounded-none border-none"
            >
              <Minus className="h-4 w-4" />
            </Button>
            <span className="h-10 flex items-center px-4 text-sm font-light min-w-12 justify-center border-l border-r border-border">
              {quantity}
            </span>
            <Button
              variant="ghost"
              size="sm"
              onClick={incrementQuantity}
              className="h-10 w-10 p-0 hover:bg-transparent hover:opacity-50 rounded-none border-none"
            >
              <Plus className="h-4 w-4" />
            </Button>
          </div>
        </div>

        <div className="flex gap-3">
          <Button
            className="flex-1 h-12 bg-foreground text-background hover:bg-foreground/90 font-light rounded-none"
            onClick={handleAddToCart}
            disabled={!canAddToCart}
          >
            {!hasCompleteVariantSelection
              ? "Select options"
              : !isPurchasable
                ? "Out of Stock"
                : adding
                  ? "Adding..."
                  : "Add to Bag"}
          </Button>
          <Button
            variant="outline"
            className="h-12 w-12 shrink-0 rounded-none border-border hover:bg-transparent"
            onClick={() => toggleWishlist(product.id, selectedVariantId)}
            aria-label={wishlisted ? "Remove from favorites" : "Add to favorites"}
          >
            <Heart
              className={`h-5 w-5 transition-colors ${wishlisted ? "fill-red-500 text-red-500" : "text-foreground"}`}
            />
          </Button>
        </div>
      </div>
    </div>
  );
};

export default ProductInfo;
