// apps/soja-next/src/app/product/[slug]/page.tsx
/** biome-ignore-all lint/security/noDangerouslySetInnerHtml: JSON-LD at build time */
/** biome-ignore-all lint/style/useComponentExportOnlyModules: Next.js page conventions */
import type { SojaProductDetail } from "@ce/soja-shared/lib/product-meta";
import type { Metadata } from "next";
import { notFound } from "next/navigation";
import { Suspense } from "react";
import { OG_IMAGES, SITE_NAME, SITE_URL, TWITTER_IMAGE } from "@/lib/constants";
import { safeJsonLd } from "@/lib/safe-json-ld";
import { storefront } from "@/lib/storefront";
import { ProductContent } from "./product-content";

export const revalidate = 3600;

export async function generateStaticParams() {
  try {
    const sdk = storefront.publicStorefront();
    const { data } = await sdk.catalog.listProducts({ limit: 100 });
    return (data?.products ?? []).map((product) => ({
      slug: product.slug || product.id,
    }));
  } catch {
    return [];
  }
}

export async function generateMetadata({
  params,
}: {
  params: Promise<{ slug: string }>;
}): Promise<Metadata> {
  const { slug } = await params;

  let product: SojaProductDetail | undefined;
  try {
    const sdk = storefront.publicStorefront();
    const { data } = await sdk.catalog.getProductDetail({ product_id: slug });
    product = data?.product;
  } catch {
    product = undefined;
  }

  if (!product) return { title: "Product Not Found" };

  const image = product.images?.[0]?.url_zoom ?? product.images?.[0]?.url_standard;
  const description =
    product.short_description ??
    `${product.name} from ${SITE_NAME} — hand-crafted bioformulations from Copenhagen.`;

  return {
    title: product.name,
    description,
    openGraph: {
      title: `${product.name} | ${SITE_NAME}`,
      description,
      url: `${SITE_URL}/product/${product.slug}`,
      images: image ? [{ url: image }] : OG_IMAGES,
    },
    other: {
      "og:type": "product",
    },
    twitter: {
      title: `${product.name} | ${SITE_NAME}`,
      description,
      images: [image ?? TWITTER_IMAGE],
    },
  };
}

export default async function ProductDetailPage({ params }: { params: Promise<{ slug: string }> }) {
  const { slug } = await params;

  let product: SojaProductDetail | undefined;
  let confirmedNotFound = false;

  try {
    const sdk = storefront.publicStorefront();
    const { data, error, response } = await sdk.catalog.getProductDetail({ product_id: slug });

    if (error) {
      // Only a 404 is a real absence; other statuses stay retryable client-side.
      confirmedNotFound = response.status === 404;
    } else {
      product = data?.product;
      confirmedNotFound = !product;
    }
  } catch {
    product = undefined;
  }

  if (confirmedNotFound) {
    notFound();
  }

  const jsonLd = product
    ? [
        {
          "@context": "https://schema.org",
          "@type": "Product",
          name: product.name,
          description: product.short_description ?? `${product.name} from ${SITE_NAME}`,
          image: product.images?.[0]?.url_zoom ?? product.images?.[0]?.url_standard,
          sku: product.sku ?? product.slug,
          url: `${SITE_URL}/product/${product.slug}`,
          brand: { "@type": "Brand", name: SITE_NAME },
          offers: {
            "@type": "Offer",
            url: `${SITE_URL}/product/${product.slug}`,
            priceCurrency: product.pricing.currency,
            price: product.pricing.selling_price,
            availability:
              product.stock_available || product.backorder
                ? "https://schema.org/InStock"
                : "https://schema.org/OutOfStock",
          },
          ...(product.reviews_count > 0
            ? {
                aggregateRating: {
                  "@type": "AggregateRating",
                  ratingValue: (product.reviews_rating_sum / product.reviews_count).toFixed(1),
                  reviewCount: product.reviews_count,
                },
              }
            : {}),
        },
        {
          "@context": "https://schema.org",
          "@type": "BreadcrumbList",
          itemListElement: [
            { "@type": "ListItem", position: 1, name: "Home", item: SITE_URL },
            ...(product.categories?.[0]
              ? [
                  {
                    "@type": "ListItem",
                    position: 2,
                    name: product.categories[0].name,
                    item: `${SITE_URL}/category/${product.categories[0].slug}`,
                  },
                ]
              : []),
            {
              "@type": "ListItem",
              position: product.categories?.[0] ? 3 : 2,
              name: product.name,
            },
          ],
        },
      ]
    : [];

  return (
    <>
      {jsonLd.map((schema) => (
        <script
          key={schema["@type"]}
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: safeJsonLd(schema) }}
        />
      ))}
      <Suspense fallback={<div className="min-h-svh bg-background" />}>
        <ProductContent serverProduct={product} />
      </Suspense>
    </>
  );
}

// apps/linea-svelte/src/routes/product/[slug]/+page.svelte
<script lang="ts">
import ProductContent from "$lib/components/ProductContent.svelte";
import { SITE_NAME, SITE_URL } from "$lib/seo";

let { data } = $props();

const product = $derived(data.product);
const title = $derived(product.seo?.title || `${product.name} | ${SITE_NAME}`);
const description = $derived(
  product.seo?.description || product.short_description || `Shop ${product.name} from ${SITE_NAME}`,
);
const image = $derived(product.images?.[0]?.url_zoom ?? product.images?.[0]?.url_standard ?? "");
const url = $derived(`${SITE_URL}/product/${product.slug}`);

const jsonLd = $derived([
  {
    "@context": "https://schema.org",
    "@type": "Product",
    name: product.name,
    description,
    image,
    sku: product.sku ?? product.slug,
    url,
    brand: { "@type": "Brand", name: SITE_NAME },
    offers: {
      "@type": "Offer",
      url,
      priceCurrency: product.pricing.currency,
      price: product.pricing.selling_price,
      availability:
        product.stock_available || product.backorder
          ? "https://schema.org/InStock"
          : "https://schema.org/OutOfStock",
    },
    ...(product.reviews_count > 0
      ? {
          aggregateRating: {
            "@type": "AggregateRating",
            ratingValue: (product.reviews_rating_sum / product.reviews_count).toFixed(1),
            reviewCount: product.reviews_count,
          },
        }
      : {}),
  },
  {
    "@context": "https://schema.org",
    "@type": "BreadcrumbList",
    itemListElement: [
      { "@type": "ListItem", position: 1, name: "Home", item: SITE_URL },
      ...(product.categories?.[0]
        ? [
            {
              "@type": "ListItem",
              position: 2,
              name: product.categories[0].name,
              item: `${SITE_URL}/category/${product.categories[0].slug}`,
            },
          ]
        : []),
      {
        "@type": "ListItem",
        position: product.categories?.[0] ? 3 : 2,
        name: product.name,
      },
    ],
  },
]);
</script>

<svelte:head>
	<title>{title}</title>
	<meta name="description" content={description} />
	<link rel="canonical" href={url} />
	<meta property="og:title" content={title} />
	<meta property="og:description" content={description} />
	<meta property="og:url" content={url} />
	<meta property="og:type" content="product" />
	{#if image}
		<meta property="og:image" content={image} />
	{/if}
	<meta name="twitter:title" content={title} />
	<meta name="twitter:description" content={description} />
	{#if image}
		<meta name="twitter:image" content={image} />
	{/if}
	{#each jsonLd as schema}
		{@html `<script type="application/ld+json">${JSON.stringify(schema)}</script>`}
	{/each}
</svelte:head>

<div class="pt-6">
	{#key data.product.id}
		<ProductContent product={data.product} similarItems={data.similarItems} />
	{/key}
</div>
