// apps/linea-svelte/src/routes/+page.svelte
<script lang="ts">
import EditorialSection from "$lib/components/EditorialSection.svelte";
import FiftyFiftySection from "$lib/components/FiftyFiftySection.svelte";
import LargeHero from "$lib/components/LargeHero.svelte";
import OneThirdTwoThirdsSection from "$lib/components/OneThirdTwoThirdsSection.svelte";
import ProductCarousel from "$lib/components/ProductCarousel.svelte";
import { DEFAULT_DESCRIPTION, FRAMEWORK, SITE_NAME, SITE_URL } from "$lib/seo";

let { data } = $props();

const HOME_TITLE = `${SITE_NAME} — Commerce Engine + ${FRAMEWORK} Starter Template`;

const jsonLd = [
  {
    "@context": "https://schema.org",
    "@type": "WebSite",
    name: SITE_NAME,
    url: SITE_URL,
    description: DEFAULT_DESCRIPTION,
    potentialAction: {
      "@type": "SearchAction",
      target: {
        "@type": "EntryPoint",
        urlTemplate: `${SITE_URL}/search?q={search_term_string}`,
      },
      "query-input": "required name=search_term_string",
    },
  },
  {
    "@context": "https://schema.org",
    "@type": "Organization",
    name: "Commerce Engine",
    url: "https://www.commercengine.io",
    logo: `${SITE_URL}/favicon.svg`,
    description: `Commerce Engine is a headless e-commerce platform. ${SITE_NAME} is an open-source reference storefront built with ${FRAMEWORK}.`,
  },
];
</script>

<svelte:head>
	<title>{HOME_TITLE}</title>
	<meta name="description" content={DEFAULT_DESCRIPTION} />
	<link rel="canonical" href={SITE_URL} />
	<meta property="og:title" content={HOME_TITLE} />
	<meta property="og:description" content={DEFAULT_DESCRIPTION} />
	<meta property="og:type" content="website" />
	<meta property="og:url" content={SITE_URL} />
	{#each jsonLd as schema}
		{@html `<script type="application/ld+json">${JSON.stringify(schema)}</script>`}
	{/each}
</svelte:head>

<div class="pt-6">
	<FiftyFiftySection />
	<ProductCarousel items={data.products} />
	<LargeHero />
	<OneThirdTwoThirdsSection />
	<EditorialSection />
</div>

// apps/linea-ssr/src/routes/index.tsx
import { createFileRoute } from "@tanstack/react-router";
import EditorialSection from "@/components/content/EditorialSection";
import FiftyFiftySection from "@/components/content/FiftyFiftySection";
import LargeHero from "@/components/content/LargeHero";
import OneThirdTwoThirdsSection from "@/components/content/OneThirdTwoThirdsSection";
import ProductCarousel from "@/components/content/ProductCarousel";
import Footer from "@/components/footer/Footer";
import Header from "@/components/header/Header";
import { storefront } from "@/lib/storefront";

const SITE_URL = "https://linea-static.demo.commercengine.io";
const SITE_NAME = "Linea";

export const Route = createFileRoute("/")({
  loader: async () => {
    const sdk = storefront.publicStorefront();
    const { data, error } = await sdk.catalog.listProducts({ page: 1, limit: 20 });
    if (error) throw new Error(error.message);
    return { products: data?.products ?? [] };
  },
  head: () => ({
    meta: [
      {
        title: `${SITE_NAME} - Minimalist jewelry crafted for the modern individual`,
      },
      {
        name: "description",
        content:
          "Shop Linea's curated collection of minimalist jewelry — rings, necklaces, earrings, and bracelets crafted for the modern individual. Free shipping on all orders.",
      },
      {
        property: "og:title",
        content: `${SITE_NAME} - Minimalist jewelry crafted for the modern individual`,
      },
      { property: "og:type", content: "website" },
      { property: "og:image", content: `${SITE_URL}/og-image.jpg` },
      { property: "og:url", content: SITE_URL },
      { name: "twitter:card", content: "summary_large_image" },
      {
        name: "twitter:title",
        content: `${SITE_NAME} - Minimalist jewelry crafted for the modern individual`,
      },
      {
        name: "twitter:description",
        content:
          "Shop Linea's curated collection of minimalist jewelry — rings, necklaces, earrings, and bracelets crafted for the modern individual.",
      },
      { name: "twitter:image", content: `${SITE_URL}/og-image.jpg` },
    ],
    links: [{ rel: "canonical", href: SITE_URL }],
    scripts: [
      {
        type: "application/ld+json",
        children: JSON.stringify({
          "@context": "https://schema.org",
          "@type": "WebSite",
          name: SITE_NAME,
          url: SITE_URL,
          potentialAction: {
            "@type": "SearchAction",
            target: {
              "@type": "EntryPoint",
              urlTemplate: `${SITE_URL}/search?q={search_term_string}`,
            },
            "query-input": "required name=search_term_string",
          },
        }),
      },
      {
        type: "application/ld+json",
        children: JSON.stringify({
          "@context": "https://schema.org",
          "@type": "Organization",
          name: SITE_NAME,
          url: SITE_URL,
          logo: `${SITE_URL}/favicon.svg`,
        }),
      },
    ],
  }),
  component: IndexPage,
});

function IndexPage() {
  const { products } = Route.useLoaderData();

  return (
    <div className="min-h-screen bg-background">
      <Header />
      <main className="pt-6">
        <FiftyFiftySection />
        <ProductCarousel serverProducts={products} />
        <LargeHero />
        <OneThirdTwoThirdsSection />
        <EditorialSection />
      </main>
      <Footer />
    </div>
  );
}
