// apps/linea-svelte/src/lib/components/about/StoreMap.svelte
<script lang="ts">
const stores = [
  {
    name: "LINEA Madison Avenue",
    address: "789 Madison Avenue, New York, NY 10065",
  },
  {
    name: "LINEA Beverly Hills",
    address: "456 Rodeo Drive, Beverly Hills, CA 90210",
  },
  {
    name: "LINEA SoHo",
    address: "123 Spring Street, New York, NY 10012",
  },
];
</script>

<div class="w-full h-96 rounded-lg overflow-hidden border border-border bg-muted/10 relative">
	<iframe
		src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d12063.046788464958!2d-74.0059413!3d40.7489054!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x89c259a9b3117469%3A0xd134e199a405a163!2sNew%20York%2C%20NY%2C%20USA!5e0!3m2!1sen!2sus!4v1641234567890!5m2!1sen!2sus"
		width="100%"
		height="100%"
		style="border: 0;"
		allowfullscreen
		loading="lazy"
		referrerpolicy="no-referrer-when-downgrade"
		class="w-full h-full"
		title="Store locations map"
	></iframe>

	<div class="absolute top-4 left-4 bg-background/90 backdrop-blur-sm rounded-lg p-4 max-w-xs">
		<h4 class="text-sm font-medium text-foreground mb-3">Our Locations</h4>
		<div class="space-y-2">
			{#each stores as store (store.name)}
				<div class="text-xs">
					<div class="flex items-center gap-2 mb-1">
						<div class="w-2 h-2 bg-primary rounded-full flex-shrink-0"></div>
						<span class="font-medium text-foreground">{store.name}</span>
					</div>
					<p class="text-muted-foreground ml-4">{store.address}</p>
				</div>
			{/each}
		</div>
	</div>
</div>

// apps/linea-ssr/src/components/about/StoreMap.tsx
interface Store {
  name: string;
  address: string;
  phone: string;
  hours: string;
  lat: number;
  lng: number;
}

const stores: Store[] = [
  {
    name: "LINEA Madison Avenue",
    address: "789 Madison Avenue, New York, NY 10065",
    phone: "+1 (212) 555-0123",
    hours: "Mon-Sat: 10AM-8PM, Sun: 12PM-6PM",
    lat: 40.7614,
    lng: -73.9776,
  },
  {
    name: "LINEA Beverly Hills",
    address: "456 Rodeo Drive, Beverly Hills, CA 90210",
    phone: "+1 (310) 555-0456",
    hours: "Mon-Sat: 10AM-8PM, Sun: 12PM-6PM",
    lat: 34.0696,
    lng: -118.4014,
  },
  {
    name: "LINEA SoHo",
    address: "123 Spring Street, New York, NY 10012",
    phone: "+1 (212) 555-0789",
    hours: "Mon-Sat: 11AM-8PM, Sun: 12PM-7PM",
    lat: 40.7253,
    lng: -74.0022,
  },
];

const StoreMap = () => {
  return (
    <div className="w-full h-96 rounded-lg overflow-hidden border border-border bg-muted/10 relative">
      {/* Static Map using Google Maps Embed API */}
      <iframe
        src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d12063.046788464958!2d-74.0059413!3d40.7489054!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x89c259a9b3117469%3A0xd134e199a405a163!2sNew%20York%2C%20NY%2C%20USA!5e0!3m2!1sen!2sus!4v1641234567890!5m2!1sen!2sus"
        width="100%"
        height="100%"
        style={{ border: 0 }}
        allowFullScreen
        loading="lazy"
        referrerPolicy="no-referrer-when-downgrade"
        className="w-full h-full"
        title="Store locations map"
      />

      {/* Overlay with store markers */}
      <div className="absolute top-4 left-4 bg-background/90 backdrop-blur-sm rounded-lg p-4 max-w-xs">
        <h4 className="text-sm font-medium text-foreground mb-3">Our Locations</h4>
        <div className="space-y-2">
          {stores.map((store) => (
            <div key={store.name} className="text-xs">
              <div className="flex items-center gap-2 mb-1">
                <div className="w-2 h-2 bg-primary rounded-full flex-shrink-0"></div>
                <span className="font-medium text-foreground">{store.name}</span>
              </div>
              <p className="text-muted-foreground ml-4">{store.address}</p>
            </div>
          ))}
        </div>
      </div>
    </div>
  );
};

export default StoreMap;
