// apps/linea/src/components/product/ProductImageGallery.tsx
import type { ProductImage } from "@commercengine/storefront-sdk";
import type * as React from "react";
import { useRef, useState } from "react";
import ImageZoom from "./ImageZoom";

interface ProductImageGalleryProps {
  images: ProductImage[];
  productName: string;
}

const ProductImageGallery = ({ images, productName }: ProductImageGalleryProps) => {
  const [currentImageIndex, setCurrentImageIndex] = useState(0);
  const [isZoomOpen, setIsZoomOpen] = useState(false);
  const [zoomInitialIndex, setZoomInitialIndex] = useState(0);
  const touchStartX = useRef<number | null>(null);
  const touchEndX = useRef<number | null>(null);

  const imageUrls = images.map((img) => img.url_zoom || img.url_standard);

  const nextImage = () => {
    setCurrentImageIndex((prev) => (prev + 1) % images.length);
  };

  const prevImage = () => {
    setCurrentImageIndex((prev) => (prev - 1 + images.length) % images.length);
  };

  const handleImageClick = (index: number) => {
    setZoomInitialIndex(index);
    setIsZoomOpen(true);
  };

  const handleTouchStart = (e: React.TouchEvent) => {
    touchStartX.current = e.touches[0].clientX;
  };

  const handleTouchMove = (e: React.TouchEvent) => {
    touchEndX.current = e.touches[0].clientX;
  };

  const handleTouchEnd = () => {
    if (!touchStartX.current || !touchEndX.current) return;

    const difference = touchStartX.current - touchEndX.current;
    const minSwipeDistance = 50;

    if (Math.abs(difference) > minSwipeDistance) {
      if (difference > 0) {
        nextImage();
      } else {
        prevImage();
      }
    }

    touchStartX.current = null;
    touchEndX.current = null;
  };

  if (images.length === 0) {
    return (
      <div className="w-full aspect-square bg-muted/10 flex items-center justify-center">
        <p className="text-sm text-muted-foreground">No images</p>
      </div>
    );
  }

  return (
    <div className="w-full">
      {/* Desktop: Vertical scrolling gallery */}
      <div className="hidden lg:block">
        <div className="space-y-4">
          {images.map((image, index) => {
            const handleKeyDown = (e: React.KeyboardEvent) => {
              if (e.key === "Enter" || e.key === " ") {
                e.preventDefault();
                handleImageClick(index);
              }
            };
            return (
              <button
                key={image.id}
                type="button"
                className="w-full aspect-square overflow-hidden cursor-pointer group border-0 p-0 bg-transparent"
                onClick={() => handleImageClick(index)}
                onKeyDown={handleKeyDown}
                aria-label={`View ${productName} image ${index + 1}`}
              >
                <img
                  src={image.url_standard}
                  alt={image.alternate_text || `${productName} view ${index + 1}`}
                  className="w-full h-full object-cover transition-transform duration-300 group-hover:scale-105"
                  loading={index === 0 ? "eager" : "lazy"}
                  fetchPriority={index === 0 ? "high" : undefined}
                  decoding="async"
                />
              </button>
            );
          })}
        </div>
      </div>

      {/* Tablet/Mobile: Image slider */}
      <div className="lg:hidden">
        <div className="relative">
          <button
            type="button"
            className="w-full aspect-square overflow-hidden cursor-pointer group touch-pan-y border-0 p-0 bg-transparent"
            onClick={() => handleImageClick(currentImageIndex)}
            onKeyDown={(e) => {
              if (e.key === "Enter" || e.key === " ") {
                e.preventDefault();
                handleImageClick(currentImageIndex);
              }
            }}
            onTouchStart={handleTouchStart}
            onTouchMove={handleTouchMove}
            onTouchEnd={handleTouchEnd}
            aria-label={`View ${productName} image ${currentImageIndex + 1}`}
          >
            <img
              src={images[currentImageIndex].url_standard}
              alt={
                images[currentImageIndex].alternate_text ||
                `${productName} view ${currentImageIndex + 1}`
              }
              className="w-full h-full object-cover transition-transform duration-300 group-hover:scale-105 select-none"
              fetchPriority="high"
              decoding="async"
            />
          </button>

          {/* Dots indicator */}
          <div className="flex justify-center mt-4 gap-2">
            {images.map((image, index) => (
              <button
                key={image.id}
                type="button"
                onClick={() => setCurrentImageIndex(index)}
                className={`w-2 h-2 rounded-full transition-colors ${
                  index === currentImageIndex ? "bg-foreground" : "bg-muted"
                }`}
                aria-label={`Go to image ${index + 1}`}
              />
            ))}
          </div>
        </div>
      </div>

      {/* Image Zoom Modal */}
      <ImageZoom
        images={imageUrls}
        initialIndex={zoomInitialIndex}
        isOpen={isZoomOpen}
        onClose={() => setIsZoomOpen(false)}
      />
    </div>
  );
};

export default ProductImageGallery;

// apps/little-things-svelte/src/lib/components/product/ProductImageGallery.svelte
<script lang="ts">
import type { ProductImage } from "@commercengine/storefront";
import StorefrontImage from "../StorefrontImage.svelte";
import ImageZoom from "./ImageZoom.svelte";

interface Props {
  images: ProductImage[];
  productName: string;
}

let { images, productName }: Props = $props();

let currentImageIndex = $state(0);
let isZoomOpen = $state(false);

const activeImage = $derived(images[currentImageIndex] ?? images[0]);

$effect(() => {
  const maxIndex = images.length - 1;
  if (maxIndex < 0) {
    currentImageIndex = 0;
    isZoomOpen = false;
    return;
  }
  if (currentImageIndex > maxIndex) currentImageIndex = maxIndex;
});
</script>

{#if images.length === 0}
	<div class="flex aspect-square w-full items-center justify-center bg-secondary">
		<p class="text-sm text-muted-foreground">No image</p>
	</div>
{:else}
	<div class="w-full">
		<div class="flex gap-4">
			<!-- Vertical thumbnail column (desktop) -->
			{#if images.length > 1}
				<div class="hidden w-20 shrink-0 flex-col gap-3 lg:flex">
					{#each images as image, index (image.id)}
						<button
							type="button"
							onclick={() => (currentImageIndex = index)}
							class="flex aspect-square items-center justify-center overflow-hidden bg-secondary p-2 transition-all {index ===
							currentImageIndex
								? 'ring-2 ring-brand'
								: 'opacity-70 hover:opacity-100'}"
							aria-label={`Show ${productName} image ${index + 1}`}
						>
							<StorefrontImage
								{image}
								alt={image.alternate_text || `${productName} thumbnail ${index + 1}`}
								variant="thumbnail"
								width={120}
								height={120}
								class="h-full w-full object-contain"
							/>
						</button>
					{/each}
				</div>
			{/if}

			<!-- Main image -->
			<button
				type="button"
				class="group flex aspect-square flex-1 items-center justify-center overflow-hidden border-0 bg-secondary p-3 md:p-4"
				onclick={() => (isZoomOpen = true)}
				aria-label={`Zoom ${productName}`}
			>
				<StorefrontImage
					image={activeImage}
					alt={activeImage.alternate_text || productName}
					variant="standard"
					width={900}
					height={900}
					loading="eager"
					fetchpriority="high"
					class="h-full w-full object-contain transition-transform duration-500 group-hover:scale-105"
				/>
			</button>
		</div>

		<!-- Mobile: horizontal thumbnail strip -->
		{#if images.length > 1}
			<div class="mt-3 flex gap-2.5 overflow-x-auto px-1 py-1 lg:hidden">
				{#each images as image, index (image.id)}
					<button
						type="button"
						onclick={() => (currentImageIndex = index)}
						class="flex size-16 shrink-0 items-center justify-center overflow-hidden bg-secondary p-1.5 transition-all {index ===
						currentImageIndex
							? 'ring-2 ring-brand'
							: 'opacity-70 hover:opacity-100'}"
						aria-label={`Show ${productName} image ${index + 1}`}
					>
						<StorefrontImage
							{image}
							alt={image.alternate_text || `${productName} thumbnail ${index + 1}`}
							variant="thumbnail"
							width={96}
							height={96}
							class="h-full w-full object-contain"
						/>
					</button>
				{/each}
			</div>
		{/if}

		<ImageZoom
			{images}
			initialIndex={currentImageIndex}
			isOpen={isZoomOpen}
			onclose={() => (isZoomOpen = false)}
		/>
	</div>
{/if}
