// apps/little-things-svelte/src/lib/components/product/RelatedProducts.svelte
<script lang="ts">
import type { Item } from "@commercengine/storefront";
import ProductSection from "../category/ProductSection.svelte";

interface Props {
  items: Item[];
  title?: string;
}

let { items, title = "You might also like" }: Props = $props();
</script>

<ProductSection {title} {items} />

// apps/little-things-tanstack/src/components/product/RelatedProducts.tsx
import { useListSkus, useSimilarProducts } from "@/lib/hooks";
import ProductSection from "../category/ProductSection";

interface RelatedProductsProps {
  productId?: string;
  title?: string;
}

const RelatedProducts = ({ productId, title = "You might also like" }: RelatedProductsProps) => {
  const similar = useSimilarProducts(productId ?? "");
  const fallback = useListSkus({ limit: 4, enabled: !productId });
  const items = productId ? similar.items : fallback.skus;

  return <ProductSection title={title} items={items} />;
};

export default RelatedProducts;
