// apps/linea/src/components/category/CategoryHeader.tsx
import { Link } from "react-router-dom";
import {
  Breadcrumb,
  BreadcrumbItem,
  BreadcrumbLink,
  BreadcrumbList,
  BreadcrumbPage,
  BreadcrumbSeparator,
} from "@/components/ui/breadcrumb";

interface CategoryHeaderProps {
  category: string;
}

const CategoryHeader = ({ category }: CategoryHeaderProps) => {
  const capitalizedCategory = category.charAt(0).toUpperCase() + category.slice(1);

  return (
    <section className="w-full px-6 mb-8">
      <div className="mb-6">
        <Breadcrumb>
          <BreadcrumbList>
            <BreadcrumbItem>
              <BreadcrumbLink asChild>
                <Link to="/">Home</Link>
              </BreadcrumbLink>
            </BreadcrumbItem>
            <BreadcrumbSeparator />
            <BreadcrumbItem>
              <BreadcrumbPage>{capitalizedCategory}</BreadcrumbPage>
            </BreadcrumbItem>
          </BreadcrumbList>
        </Breadcrumb>
      </div>

      <div>
        <h1 className="text-3xl md:text-4xl font-light text-foreground">{capitalizedCategory}</h1>
      </div>
    </section>
  );
};

export default CategoryHeader;

// apps/linea-svelte/src/lib/components/CategoryHeader.svelte
<script lang="ts">
let { category }: { category: string } = $props();

const capitalizedCategory = $derived(category.charAt(0).toUpperCase() + category.slice(1));
</script>

<section class="w-full px-6 mb-8">
	<div class="mb-6">
		<nav aria-label="Breadcrumb">
			<ol class="flex items-center gap-1.5 text-sm text-muted-foreground">
				<li><a href="/" class="hover:text-foreground transition-colors">Home</a></li>
				<li class="text-muted-foreground/50">/</li>
				<li class="text-foreground">{capitalizedCategory}</li>
			</ol>
		</nav>
	</div>
	<h1 class="text-3xl md:text-4xl font-light text-foreground">{capitalizedCategory}</h1>
</section>
