// apps/linea/src/components/content/ProductCarousel.tsx
import { Link } from "react-router-dom";
import { Card, CardContent } from "@/components/ui/card";
import { Carousel, CarouselContent, CarouselItem } from "@/components/ui/carousel";
import WishlistButton from "@/components/WishlistButton";
import { formatPrice } from "@/lib/format";
import { useProducts } from "@/lib/hooks";
import { useWishlist } from "@/lib/wishlist";

const ProductCarousel = () => {
  const { products, isLoading } = useProducts({ limit: 6 });
  const { isInWishlist, toggleWishlist } = useWishlist();

  if (isLoading) {
    const skeletonIds = ["c1", "c2", "c3", "c4"];
    return (
      <section className="w-full mb-16 px-6">
        <div className="flex gap-4">
          {skeletonIds.map((id) => (
            <div key={id} className="basis-1/2 md:basis-1/3 lg:basis-1/4 shrink-0">
              <div className="aspect-square bg-muted/20 animate-pulse mb-3" />
              <div className="h-4 w-20 bg-muted/20 animate-pulse mb-1" />
              <div className="h-4 w-32 bg-muted/20 animate-pulse" />
            </div>
          ))}
        </div>
      </section>
    );
  }

  return (
    <section className="w-full mb-16 px-6">
      <Carousel
        opts={{
          align: "start",
          loop: false,
        }}
        className="w-full"
      >
        <CarouselContent className="">
          {products.map((product) => (
            <CarouselItem
              key={product.id}
              className="basis-1/2 md:basis-1/3 lg:basis-1/4 pr-2 md:pr-4"
            >
              <Link to={`/product/${product.slug}`}>
                <Card className="border-none shadow-none bg-transparent group">
                  <CardContent className="p-0">
                    <div className="aspect-square mb-3 overflow-hidden bg-muted/10 relative">
                      <img
                        src={product.images?.[0]?.url_standard}
                        alt={product.images?.[0]?.alternate_text || product.name}
                        className="w-full h-full object-cover transition-all duration-300 group-hover:opacity-0"
                        loading="lazy"
                        decoding="async"
                      />
                      <img
                        src={product.images?.[1]?.url_standard || product.images?.[0]?.url_standard}
                        alt={`${product.name} alternate`}
                        className="absolute inset-0 w-full h-full object-cover transition-all duration-300 opacity-0 group-hover:opacity-100"
                        loading="lazy"
                        decoding="async"
                      />
                      <div className="absolute inset-0 bg-black/[0.03]" />
                      <WishlistButton
                        active={isInWishlist(product.id)}
                        onClick={(e) => {
                          e.preventDefault();
                          e.stopPropagation();
                          toggleWishlist(product.id);
                        }}
                      />
                    </div>
                    <div className="space-y-1">
                      <p className="text-sm font-light text-foreground">
                        {product.categories?.[0]?.name}
                      </p>
                      <div className="flex justify-between items-center">
                        <h3 className="text-sm font-medium text-foreground">{product.name}</h3>
                        <p className="text-sm font-light text-foreground">
                          {formatPrice(product.pricing.selling_price, product.pricing.currency)}
                        </p>
                      </div>
                    </div>
                  </CardContent>
                </Card>
              </Link>
            </CarouselItem>
          ))}
        </CarouselContent>
      </Carousel>
    </section>
  );
};

export default ProductCarousel;

// apps/linea-svelte/src/lib/components/ProductCarousel.svelte
<script lang="ts">
import { formatPrice } from "@ce/ui/lib/format";
import type { Item } from "@commercengine/storefront";
import { routeToHref } from "$lib/linea-routing";
import { wishlist } from "$lib/wishlist.svelte";
import StorefrontImage from "./StorefrontImage.svelte";
import WishlistButton from "./WishlistButton.svelte";

interface Props {
  items: Item[];
  isLoading?: boolean;
}

let { items, isLoading = false }: Props = $props();

const skeletonIds = ["c1", "c2", "c3", "c4"];

function getItemHref(item: Item): string {
  return routeToHref({
    path: `/product/${item.product_slug}`,
    search: item.variant_slug ? { variant: item.variant_slug } : undefined,
  });
}

function handleWishlistClick(e: MouseEvent, item: Item) {
  e.preventDefault();
  e.stopPropagation();
  wishlist.toggleWishlist(item.product_id, item.variant_id);
}
</script>

{#if isLoading}
	<section class="w-full mb-16 px-6">
		<div class="flex gap-4">
			{#each skeletonIds as id (id)}
				<div class="basis-1/2 md:basis-1/3 lg:basis-1/4 shrink-0">
					<div class="aspect-square bg-muted/20 animate-pulse mb-3"></div>
					<div class="h-4 w-20 bg-muted/20 animate-pulse mb-1"></div>
					<div class="h-4 w-32 bg-muted/20 animate-pulse"></div>
				</div>
			{/each}
		</div>
	</section>
{:else}
	<section class="w-full mb-16 px-6">
		<div class="flex w-full overflow-x-auto snap-x snap-mandatory gap-2 md:gap-4">
			{#each items as item (`${item.product_id}:${item.variant_id ?? 'product'}`)}
				<div class="basis-1/2 md:basis-1/3 lg:basis-1/4 shrink-0 snap-start">
					<a href={getItemHref(item)} class="block group">
						<div class="aspect-square mb-3 overflow-hidden bg-muted/10 relative">
							<StorefrontImage
								image={item.images?.[0]}
								alt={item.images?.[0]?.alternate_text || item.product_name}
								variant="standard"
								sizes="(max-width: 768px) calc(50vw - 32px), (max-width: 1024px) calc(33vw - 32px), calc(25vw - 32px)"
								width={400}
								height={400}
								loading="lazy"
								class="w-full h-full object-cover transition-all duration-300 group-hover:opacity-0"
							/>
							<StorefrontImage
								image={item.images?.[1] || item.images?.[0]}
								alt="{item.variant_name || item.product_name} alternate"
								variant="standard"
								sizes="(max-width: 768px) calc(50vw - 32px), (max-width: 1024px) calc(33vw - 32px), calc(25vw - 32px)"
								width={400}
								height={400}
								loading="lazy"
								class="absolute inset-0 w-full h-full object-cover transition-all duration-300 opacity-0 group-hover:opacity-100"
							/>
							<div class="absolute inset-0 bg-black/[0.03]"></div>
							<WishlistButton
								active={wishlist.isInWishlist(item.product_id, item.variant_id)}
								onclick={(e) => handleWishlistClick(e, item)}
							/>
						</div>
						<div class="space-y-1">
							<p class="text-sm font-light text-foreground">
								{item.categories?.[0]?.name}
							</p>
							<div class="flex justify-between items-center">
								<h3 class="text-sm font-medium text-foreground">
									{item.variant_name || item.product_name}
								</h3>
								<p class="text-sm font-light text-foreground">
									{formatPrice(item.pricing.selling_price, item.pricing.currency)}
								</p>
							</div>
						</div>
					</a>
				</div>
			{/each}
		</div>
	</section>
{/if}
