// apps/linea/src/components/about/ContentSection.tsx
interface ContentSectionProps {
  title?: string;
  children: React.ReactNode;
  className?: string;
}

const ContentSection = ({ title, children, className = "" }: ContentSectionProps) => {
  return (
    <section className={`pr-6 py-16 ${className}`}>
      {title && <h2 className="text-3xl font-light text-foreground mb-8">{title}</h2>}
      {children}
    </section>
  );
};

export default ContentSection;

// apps/linea-svelte/src/lib/components/about/ContentSection.svelte
<script lang="ts">
import type { Snippet } from "svelte";

let {
  title,
  children,
  class: className = "",
}: { title?: string; children: Snippet; class?: string } = $props();
</script>

<section class="pr-6 py-16 {className}">
	{#if title}
		<h2 class="text-3xl font-light text-foreground mb-8">{title}</h2>
	{/if}
	{@render children()}
</section>
