// apps/soja-next/src/app/category-content.tsx
"use client";

import { CategoryFilterRow, PLPHero, ProductGrid, SortSelect } from "@ce/soja-shared/category";
import { BrandPillars } from "@ce/soja-shared/content";
import { categoryTitleFromSlug, matchCategory } from "@ce/soja-shared/lib/category-slug";
import type { SojaRoute } from "@ce/soja-shared/lib/routing";
import type { Category, Item, Pagination } from "@commercengine/storefront";
import { useMemo, useState } from "react";
import { buildFilter } from "@/lib/build-filter";
import { useCategories, useSearchProducts } from "@/lib/hooks";
import { PLP_COPY, SHOP_CATEGORIES } from "@/lib/site-content";
import { SojaLink } from "@/lib/soja-routing";
import { useWishlist } from "@/lib/wishlist";

const PAGE_SIZE = 12;

interface CategoryContentProps {
  categorySlug?: string;
  categoryName?: string;
  categoryDescription?: string;
  categories?: Category[];
  initialSkus: Item[];
  initialPagination: Pagination | undefined;
}

export function CategoryContent({
  categorySlug,
  categoryName: serverCategoryName,
  categoryDescription,
  categories: serverCategories,
  initialSkus,
  initialPagination,
}: CategoryContentProps) {
  const [page, setPage] = useState(1);
  const [sort, setSort] = useState("");
  const wishlist = useWishlist();

  const needsClientCategories = !serverCategories?.length;
  const clientCategories = useCategories({ enabled: needsClientCategories });
  const categories = serverCategories?.length ? serverCategories : clientCategories.categories;

  const categoryName = serverCategoryName ?? matchCategory(categories, categorySlug)?.name;

  const categoryPending = Boolean(categorySlug) && !categoryName;

  const filterItems = useMemo(() => {
    const referenceSlugs = new Set<string>(SHOP_CATEGORIES.map((entry) => entry.slug));
    const extras = categories
      .filter((entry) => entry.slug && !referenceSlugs.has(entry.slug))
      .map((entry) => ({ label: entry.name, slug: entry.slug as string }));

    return [
      { label: "All products", slug: null },
      ...SHOP_CATEGORIES.map((entry) => ({ label: entry.label, slug: entry.slug })),
      ...extras,
    ].map((entry) => ({
      label: entry.label,
      route: (entry.slug
        ? { path: `/category/${entry.slug}` }
        : { path: "/all-products" }) as SojaRoute,
      active: entry.slug === (categorySlug ?? null),
    }));
  }, [categories, categorySlug]);

  const filter = useMemo(() => buildFilter({}, categoryName), [categoryName]);

  // An empty initial set is indistinguishable from a failed server read, so treat
  // it as missing and let the client query recover instead of stranding the page
  // on the empty state.
  const usingInitialData = initialSkus.length > 0 && page === 1 && sort === "";

  const searchResult = useSearchProducts({
    page,
    limit: PAGE_SIZE,
    sort: sort ? [sort] : undefined,
    filter: filter.length > 0 ? filter : undefined,
    enabled: !usingInitialData && !categoryPending,
  });

  const skus = usingInitialData ? initialSkus : searchResult.skus;
  const pagination = usingInitialData ? initialPagination : searchResult.pagination;
  const isLoading = usingInitialData ? false : searchResult.isLoading;

  const slugDisplayName = categorySlug ? categoryTitleFromSlug(categorySlug) : undefined;

  const title = categoryName ?? slugDisplayName ?? PLP_COPY.title;
  const subtitle = categoryDescription || PLP_COPY.subtitle;

  const handlePageChange = (nextPage: number) => {
    setPage(nextPage);
    window.scrollTo({ top: 0, behavior: "smooth" });
  };

  return (
    <main>
      <PLPHero title={title} subtitle={subtitle} />
      <CategoryFilterRow items={filterItems} LinkComponent={SojaLink} />
      <SortSelect
        value={sort}
        onChange={(next) => {
          setSort(next);
          setPage(1);
        }}
        count={pagination?.total_records}
      />
      <ProductGrid
        skus={skus}
        isLoading={isLoading}
        LinkComponent={SojaLink}
        pagination={pagination}
        onPageChange={handlePageChange}
        wishlist={wishlist}
        emptyMessage="Nothing in this collection yet."
      />
      <BrandPillars />
    </main>
  );
}

// apps/soja-svelte/src/lib/components/category/CategoryContent.svelte
<script lang="ts">
import type { Category, Item, Pagination } from "@commercengine/storefront";
import { buildFilter } from "$lib/build-filter";
import { getSdk } from "$lib/storefront";
import { PLP_COPY, SHOP_CATEGORIES } from "$lib/site-content";
import CategoryFilterRow from "./CategoryFilterRow.svelte";
import PlpHero from "./PlpHero.svelte";
import ProductGrid from "./ProductGrid.svelte";
import SortSelect from "./SortSelect.svelte";
import BrandPillars from "../home/BrandPillars.svelte";

const PAGE_SIZE = 12;

interface Props {
  categorySlug?: string | null;
  categoryName?: string;
  categoryDescription?: string;
  categories?: Category[];
  initialSkus: Item[];
  initialPagination?: Pagination;
}

let {
  categorySlug = null,
  categoryName,
  categoryDescription,
  categories = [],
  initialSkus,
  initialPagination,
}: Props = $props();

let page = $state(1);
let sort = $state("");
let fetched = $state<{ skus: Item[]; pagination?: Pagination } | null>(null);
let isLoading = $state(false);
// Only the newest request may commit results or clear the loading flag.
let requestSeq = 0;

// An empty initial set is indistinguishable from a failed loader read, so treat it
// as missing and let the client request recover.
const usingInitialData = $derived(initialSkus.length > 0 && page === 1 && sort === "");
const skus = $derived(usingInitialData ? initialSkus : (fetched?.skus ?? []));
const pagination = $derived(usingInitialData ? initialPagination : fetched?.pagination);

const filterItems = $derived.by(() => {
  const referenceSlugs = new Set<string>(SHOP_CATEGORIES.map((entry) => entry.slug));
  const extras = categories
    .filter((entry) => entry.slug && !referenceSlugs.has(entry.slug))
    .map((entry) => ({ label: entry.name, slug: entry.slug as string }));

  return [
    { label: "All products", slug: null },
    ...SHOP_CATEGORIES.map((entry) => ({ label: entry.label, slug: entry.slug })),
    ...extras,
  ].map((entry) => ({
    label: entry.label,
    href: entry.slug ? `/category/${entry.slug}` : "/all-products",
    active: entry.slug === categorySlug,
  }));
});

async function fetchPage() {
  if (usingInitialData) {
    fetched = null;
    return;
  }

  const seq = ++requestSeq;
  isLoading = true;
  try {
    const filter = buildFilter({}, categoryName);
    const { data, error } = await getSdk().catalog.searchProducts({
      query: "",
      page,
      limit: PAGE_SIZE,
      ...(filter.length > 0 ? { filter } : {}),
      ...(sort ? { sort: [sort] } : {}),
    });
    if (error) throw new Error(error.message);
    if (seq !== requestSeq) return;
    fetched = { skus: data?.skus ?? [], pagination: data?.pagination };
  } catch (error) {
    if (seq !== requestSeq) return;
    // biome-ignore lint/suspicious/noConsole: surface catalog failures
    console.error("Failed to load products:", error);
    fetched = { skus: [] };
  } finally {
    if (seq === requestSeq) isLoading = false;
  }
}

function changeSort(next: string) {
  sort = next;
  page = 1;
  void fetchPage();
}

function changePage(next: number) {
  page = next;
  window.scrollTo({ top: 0, behavior: "smooth" });
  void fetchPage();
}
</script>

<main>
	<PlpHero
		title={categoryName ?? PLP_COPY.title}
		subtitle={categoryDescription || PLP_COPY.subtitle}
	/>
	<CategoryFilterRow items={filterItems} />
	<SortSelect value={sort} onchange={changeSort} count={pagination?.total_records} />
	<ProductGrid
		{skus}
		{isLoading}
		{pagination}
		onpagechange={changePage}
		emptyMessage="Nothing in this collection yet."
	/>
	<BrandPillars />
</main>
