// apps/linea/src/components/category/Pagination.tsx
import type { Pagination as PaginationType } from "@commercengine/storefront-sdk";
import { ChevronLeft, ChevronRight } from "lucide-react";
import { Button } from "@/components/ui/button";

interface PaginationProps {
  pagination: PaginationType;
  onPageChange: (page: number) => void;
}

function getPageNumbers(totalPages: number, currentPage: number): (number | "ellipsis")[] {
  if (totalPages <= 5) {
    return Array.from({ length: totalPages }, (_, i) => i + 1);
  }

  const pages: (number | "ellipsis")[] = [1];

  if (currentPage > 3) pages.push("ellipsis");

  const start = Math.max(2, currentPage - 1);
  const end = Math.min(totalPages - 1, currentPage + 1);

  for (let i = start; i <= end; i++) {
    pages.push(i);
  }

  if (currentPage < totalPages - 2) pages.push("ellipsis");

  pages.push(totalPages);
  return pages;
}

const Pagination = ({ pagination, onPageChange }: PaginationProps) => {
  const currentPage = pagination.next_page ? pagination.next_page - 1 : pagination.total_pages;
  const pages = getPageNumbers(pagination.total_pages, currentPage);

  return (
    <section className="w-full px-6 py-8">
      <div className="flex justify-start items-center gap-2">
        <Button
          variant="ghost"
          size="sm"
          className="p-2 hover:bg-transparent hover:opacity-50 disabled:opacity-30 -ml-2"
          disabled={!pagination.previous_page}
          onClick={() => pagination.previous_page && onPageChange(pagination.previous_page)}
        >
          <ChevronLeft className="h-4 w-4" />
        </Button>

        <div className="flex items-center gap-1">
          {pages.map((page, idx) =>
            page === "ellipsis" ? (
              <span
                key={`ellipsis-${idx}`}
                className="mx-2 text-sm font-light text-muted-foreground"
              >
                ...
              </span>
            ) : (
              <Button
                key={page}
                variant="ghost"
                size="sm"
                className={`min-w-8 h-8 hover:bg-transparent hover:underline text-sm ${
                  page === currentPage ? "underline font-normal" : "font-light"
                }`}
                onClick={() => onPageChange(page)}
              >
                {page}
              </Button>
            )
          )}
        </div>

        <Button
          variant="ghost"
          size="sm"
          className="p-2 hover:bg-transparent hover:opacity-50 disabled:opacity-30"
          disabled={!pagination.next_page}
          onClick={() => pagination.next_page && onPageChange(pagination.next_page)}
        >
          <ChevronRight className="h-4 w-4" />
        </Button>
      </div>
    </section>
  );
};

export default Pagination;

// apps/soja-svelte/src/lib/components/category/Pagination.svelte
<script lang="ts">
import type { Pagination as PaginationType } from "@commercengine/storefront";

interface Props {
  pagination: PaginationType;
  onpagechange: (page: number) => void;
}

let { pagination, onpagechange }: Props = $props();

// The API reports neighbours, not the current page.
const total = $derived(pagination.total_pages ?? 1);
const current = $derived(pagination.next_page ? pagination.next_page - 1 : total);
</script>

{#if total > 1}
	<nav aria-label="Pagination" class="soja-container flex items-center justify-between gap-6 py-16">
		<button
			type="button"
			disabled={current <= 1}
			onclick={() => onpagechange(current - 1)}
			class="text-meta transition-opacity duration-300 ease-soja hover:opacity-60 disabled:pointer-events-none disabled:opacity-30"
		>
			Previous
		</button>
		<span class="text-meta text-muted-foreground" aria-live="polite">{current} / {total}</span>
		<button
			type="button"
			disabled={current >= total}
			onclick={() => onpagechange(current + 1)}
			class="text-meta transition-opacity duration-300 ease-soja hover:opacity-60 disabled:pointer-events-none disabled:opacity-30"
		>
			Next
		</button>
	</nav>
{/if}
