// apps/linea-next/src/app/about/sustainability/page.tsx
import AboutSidebar from "@/components/about/AboutSidebar";
import ContentSection from "@/components/about/ContentSection";
import PageHeader from "@/components/about/PageHeader";

export default function SustainabilityPage() {
  return (
    <div className="flex">
      <div className="hidden lg:block">
        <AboutSidebar />
      </div>

      <main className="w-full lg:w-[70vw] lg:ml-auto px-6">
        <PageHeader
          title="Sustainability"
          subtitle="Creating beautiful jewelry while protecting our planet for future generations"
        />

        <ContentSection title="Our Environmental Commitment">
          <div className="grid md:grid-cols-2 gap-12 mb-16">
            <div className="space-y-6">
              <h3 className="text-xl font-light text-foreground">Ethical Sourcing</h3>
              <p className="text-muted-foreground leading-relaxed">
                We partner only with suppliers who share our commitment to ethical practices. Every
                gemstone and precious metal in our collection is sourced responsibly, with full
                transparency in our supply chain.
              </p>
            </div>
            <div className="space-y-6">
              <h3 className="text-xl font-light text-foreground">Recycled Materials</h3>
              <p className="text-muted-foreground leading-relaxed">
                Over 80% of our precious metals come from recycled sources, reducing the
                environmental impact of mining while maintaining the highest quality standards for
                our jewelry.
              </p>
            </div>
          </div>

          <div className="bg-muted/10 rounded-lg p-8">
            <h3 className="text-2xl font-light text-foreground mb-6">Our Impact Goals</h3>
            <div className="grid md:grid-cols-3 gap-8">
              <div>
                <div className="text-3xl font-light text-primary mb-2">100%</div>
                <p className="text-sm text-muted-foreground">Carbon neutral operations by 2025</p>
              </div>
              <div>
                <div className="text-3xl font-light text-primary mb-2">90%</div>
                <p className="text-sm text-muted-foreground">Recycled packaging materials</p>
              </div>
              <div>
                <div className="text-3xl font-light text-primary mb-2">Zero</div>
                <p className="text-sm text-muted-foreground">Waste to landfill policy</p>
              </div>
            </div>
          </div>
        </ContentSection>

        <ContentSection title="Circular Economy">
          <div className="space-y-8">
            <p className="text-lg text-muted-foreground leading-relaxed">
              We believe in the power of circular design - creating jewelry that can be treasured,
              repaired, and eventually recycled into new pieces.
            </p>

            <div className="grid md:grid-cols-2 gap-8">
              <div className="space-y-4">
                <h3 className="text-lg font-light text-foreground">Lifetime Care</h3>
                <p className="text-muted-foreground">
                  Every piece comes with our lifetime care promise, including professional cleaning,
                  repairs, and resizing services.
                </p>
              </div>
              <div className="space-y-4">
                <h3 className="text-lg font-light text-foreground">Take-Back Program</h3>
                <p className="text-muted-foreground">
                  When you're ready for something new, we'll take back your LINEA jewelry to be
                  recycled into future pieces.
                </p>
              </div>
            </div>
          </div>
        </ContentSection>

        <ContentSection title="Certifications & Partnerships">
          <div className="space-y-8">
            <p className="text-muted-foreground leading-relaxed">
              Our commitment to sustainability is verified through partnerships with leading
              organizations and certifications that hold us accountable to the highest standards.
            </p>

            <div className="grid md:grid-cols-4 gap-8 items-center">
              <div className="h-16 w-32 bg-muted/10 rounded-lg flex items-center justify-center">
                <span className="text-xs text-muted-foreground">RJC Certified</span>
              </div>
              <div className="h-16 w-32 bg-muted/10 rounded-lg flex items-center justify-center">
                <span className="text-xs text-muted-foreground">B Corp</span>
              </div>
              <div className="h-16 w-32 bg-muted/10 rounded-lg flex items-center justify-center">
                <span className="text-xs text-muted-foreground">SCS Certified</span>
              </div>
              <div className="h-16 w-32 bg-muted/10 rounded-lg flex items-center justify-center">
                <span className="text-xs text-muted-foreground">Fair Trade</span>
              </div>
            </div>
          </div>
        </ContentSection>
      </main>
    </div>
  );
}

// apps/linea-svelte/src/routes/about/sustainability/+page.svelte
<script lang="ts">
import ContentSection from "$lib/components/about/ContentSection.svelte";
import PageHeader from "$lib/components/about/PageHeader.svelte";
</script>

<PageHeader
	title="Sustainability"
	subtitle="Creating beautiful jewelry while protecting our planet for future generations"
/>

<ContentSection title="Our Environmental Commitment">
	<div class="grid md:grid-cols-2 gap-12 mb-16">
		<div class="space-y-6">
			<h3 class="text-xl font-light text-foreground">Ethical Sourcing</h3>
			<p class="text-muted-foreground leading-relaxed">
				We partner only with suppliers who share our commitment to ethical practices. Every
				gemstone and precious metal in our collection is sourced responsibly, with full
				transparency in our supply chain.
			</p>
		</div>
		<div class="space-y-6">
			<h3 class="text-xl font-light text-foreground">Recycled Materials</h3>
			<p class="text-muted-foreground leading-relaxed">
				Over 80% of our precious metals come from recycled sources, reducing the environmental
				impact of mining while maintaining the highest quality standards for our jewelry.
			</p>
		</div>
	</div>

	<div class="bg-muted/10 rounded-lg p-8">
		<h3 class="text-2xl font-light text-foreground mb-6">Our Impact Goals</h3>
		<div class="grid md:grid-cols-3 gap-8">
			<div>
				<div class="text-3xl font-light text-primary mb-2">100%</div>
				<p class="text-sm text-muted-foreground">Carbon neutral operations by 2025</p>
			</div>
			<div>
				<div class="text-3xl font-light text-primary mb-2">90%</div>
				<p class="text-sm text-muted-foreground">Recycled packaging materials</p>
			</div>
			<div>
				<div class="text-3xl font-light text-primary mb-2">Zero</div>
				<p class="text-sm text-muted-foreground">Waste to landfill policy</p>
			</div>
		</div>
	</div>
</ContentSection>

<ContentSection title="Circular Economy">
	<div class="space-y-8">
		<p class="text-lg text-muted-foreground leading-relaxed">
			We believe in the power of circular design - creating jewelry that can be treasured,
			repaired, and eventually recycled into new pieces.
		</p>

		<div class="grid md:grid-cols-2 gap-8">
			<div class="space-y-4">
				<h3 class="text-lg font-light text-foreground">Lifetime Care</h3>
				<p class="text-muted-foreground">
					Every piece comes with our lifetime care promise, including professional cleaning,
					repairs, and resizing services.
				</p>
			</div>
			<div class="space-y-4">
				<h3 class="text-lg font-light text-foreground">Take-Back Program</h3>
				<p class="text-muted-foreground">
					When you're ready for something new, we'll take back your LINEA jewelry to be recycled
					into future pieces.
				</p>
			</div>
		</div>
	</div>
</ContentSection>

<ContentSection title="Certifications & Partnerships">
	<div class="space-y-8">
		<p class="text-muted-foreground leading-relaxed">
			Our commitment to sustainability is verified through partnerships with leading organizations
			and certifications that hold us accountable to the highest standards.
		</p>

		<div class="grid md:grid-cols-4 gap-8 items-center">
			<div class="h-16 w-32 bg-muted/10 rounded-lg flex items-center justify-center">
				<span class="text-xs text-muted-foreground">RJC Certified</span>
			</div>
			<div class="h-16 w-32 bg-muted/10 rounded-lg flex items-center justify-center">
				<span class="text-xs text-muted-foreground">B Corp</span>
			</div>
			<div class="h-16 w-32 bg-muted/10 rounded-lg flex items-center justify-center">
				<span class="text-xs text-muted-foreground">SCS Certified</span>
			</div>
			<div class="h-16 w-32 bg-muted/10 rounded-lg flex items-center justify-center">
				<span class="text-xs text-muted-foreground">Fair Trade</span>
			</div>
		</div>
	</div>
</ContentSection>
