// apps/linea-ssr/src/components/about/ImageTextBlock.tsx
interface ImageTextBlockProps {
  image: string;
  imageAlt: string;
  title: string;
  content: string;
  imagePosition?: "left" | "right";
}

const ImageTextBlock = ({
  image,
  imageAlt,
  title,
  content,
  imagePosition = "left",
}: ImageTextBlockProps) => {
  return (
    <div
      className={`flex flex-col ${imagePosition === "right" ? "lg:flex-row-reverse" : "lg:flex-row"} gap-12 items-center`}
    >
      <div className="flex-1">
        <img
          src={image}
          alt={imageAlt}
          className="w-full aspect-square lg:aspect-auto lg:h-[800px] object-cover"
          loading="lazy"
          decoding="async"
        />
      </div>
      <div className="flex-1 space-y-6">
        <h3 className="text-2xl font-light text-foreground">{title}</h3>
        <p className="text-muted-foreground leading-relaxed">{content}</p>
      </div>
    </div>
  );
};

export default ImageTextBlock;

// apps/little-things-svelte/src/lib/components/about/ImageTextBlock.svelte
<script lang="ts">
interface Props {
  image: string;
  imageAlt: string;
  title: string;
  content: string;
  imagePosition?: "left" | "right";
}

let { image, imageAlt, title, content, imagePosition = "left" }: Props = $props();
</script>

<section class="w-full px-6 py-16">
	<div
		class="mx-auto grid max-w-5xl grid-cols-1 items-center gap-10 lg:grid-cols-2 {imagePosition ===
		'right'
			? 'lg:[&>*:first-child]:order-last'
			: ''}"
	>
		<div class="aspect-[4/3] overflow-hidden rounded-lg bg-muted/40">
			<img src={image} alt={imageAlt} loading="lazy" decoding="async" class="h-full w-full object-cover" />
		</div>
		<div class="space-y-4">
			<h3 class="text-2xl font-bold tracking-tight text-foreground">{title}</h3>
			<p class="text-base font-light leading-relaxed text-muted-foreground">{content}</p>
		</div>
	</div>
</section>
