// apps/little-things-svelte/src/routes/blog/[slug]/+page.svelte
<script lang="ts">
import ArticlePost from "$lib/components/blog/ArticlePost.svelte";
import { SITE_NAME, SITE_URL } from "$lib/seo";

let { data } = $props();

const article = $derived(data.article);
const title = $derived(`${article.title} | ${SITE_NAME}`);
const url = $derived(`${SITE_URL}/blog/${article.slug}`);
</script>

<svelte:head>
	<title>{title}</title>
	<meta name="description" content={article.excerpt} />
	<link rel="canonical" href={url} />
	<meta property="og:title" content={title} />
	<meta property="og:description" content={article.excerpt} />
	<meta property="og:type" content="article" />
	<meta property="og:url" content={url} />
	<meta property="og:image" content={article.image} />
</svelte:head>

<ArticlePost {article} related={data.related} />

// apps/little-things-next/src/app/blog/[slug]/page.tsx
/** biome-ignore-all lint/style/useComponentExportOnlyModules: Next.js page conventions */
import type { Metadata } from "next";
import { notFound } from "next/navigation";
import ArticlePost from "@/components/blog/ArticlePost";
import { ARTICLES, getArticleBySlug, getRelatedArticles } from "@/lib/blog-data";
import { SITE_NAME, SITE_URL } from "@/lib/constants";

export function generateStaticParams() {
  return ARTICLES.map((article) => ({ slug: article.slug }));
}

export async function generateMetadata({
  params,
}: {
  params: Promise<{ slug: string }>;
}): Promise<Metadata> {
  const { slug } = await params;
  const article = getArticleBySlug(slug);

  if (!article) return { title: "Article not found" };

  return {
    title: article.title,
    description: article.excerpt,
    openGraph: {
      title: `${article.title} | ${SITE_NAME}`,
      description: article.excerpt,
      type: "article",
      url: `${SITE_URL}/blog/${article.slug}`,
      images: [{ url: article.image }],
    },
    twitter: {
      title: `${article.title} | ${SITE_NAME}`,
      description: article.excerpt,
    },
  };
}

export default async function BlogPostPage({ params }: { params: Promise<{ slug: string }> }) {
  const { slug } = await params;
  const article = getArticleBySlug(slug);

  if (!article) {
    notFound();
  }

  return (
    <main className="pt-6">
      <ArticlePost article={article} related={getRelatedArticles(article.slug)} />
    </main>
  );
}
