// apps/little-things-next/src/app/all-products/page.tsx
/** biome-ignore-all lint/style/useComponentExportOnlyModules: Next.js page conventions */
import type { Item, Pagination } from "@commercengine/storefront";
import type { Metadata } from "next";
import { SITE_NAME, SITE_URL } from "@/lib/constants";
import { storefront } from "@/lib/storefront";
import { CategoryContent } from "../category-content";

export const revalidate = 3600;

export const metadata: Metadata = {
  title: "All products",
  description: `Browse every product from ${SITE_NAME} in one place — a tight, opinionated catalog where everything earns its spot.`,
  openGraph: {
    title: `All products | ${SITE_NAME}`,
    description: `Browse every product from ${SITE_NAME} in one place.`,
    type: "website",
    url: `${SITE_URL}/all-products`,
  },
};

export default async function AllProductsPage() {
  let skus: Item[] = [];
  let pagination: Pagination | undefined;

  try {
    const sdk = storefront.publicStorefront();
    const { data } = await sdk.catalog.listSkus({ page: 1, limit: 20 });
    skus = data?.skus ?? [];
    pagination = data?.pagination;
  } catch {
    skus = [];
  }

  return <CategoryContent initialSkus={skus} initialPagination={pagination} />;
}

// apps/little-things-svelte/src/routes/all-products/+page.svelte
<script lang="ts">
import CategoryContent from "$lib/components/category/CategoryContent.svelte";
import { DEFAULT_DESCRIPTION, SITE_NAME, SITE_URL } from "$lib/seo";

let { data } = $props();

const title = `All products | ${SITE_NAME}`;
const url = `${SITE_URL}/all-products`;
</script>

<svelte:head>
	<title>{title}</title>
	<meta name="description" content={DEFAULT_DESCRIPTION} />
	<link rel="canonical" href={url} />
	<meta property="og:title" content={title} />
	<meta property="og:description" content={DEFAULT_DESCRIPTION} />
	<meta property="og:type" content="website" />
	<meta property="og:url" content={url} />
</svelte:head>

<CategoryContent
	displayName="All products"
	categorySlug={null}
	initialSkus={data.skus}
	initialPagination={data.pagination}
/>
