// apps/little-things-next/src/app/category-content.tsx
"use client";

import type { Item, Pagination } from "@commercengine/storefront";
import { useEffect, useMemo, useRef, useState } from "react";
import FilterSortBar from "@/components/category/FilterSortBar";
import PLPHero from "@/components/category/PlpHero";
import ProductGrid from "@/components/category/ProductGrid";
import { buildFilter } from "@/lib/build-filter";
import { useCategories, useListSkus, useSearchProducts } from "@/lib/hooks";

interface CategoryContentProps {
  categorySlug?: string;
  initialSkus: Item[];
  initialPagination: Pagination | undefined;
}

export function CategoryContent({
  categorySlug,
  initialSkus,
  initialPagination,
}: CategoryContentProps) {
  const [filtersOpen, setFiltersOpen] = useState(false);
  const [page, setPage] = useState(1);
  const [filters, setFilters] = useState<Record<string, unknown>>({});

  const { categories } = useCategories();
  const matchedCategory = categorySlug
    ? categories.find(
        (c) => c.slug === categorySlug || c.name.toLowerCase().replace(/\s+/g, "-") === categorySlug
      )
    : undefined;
  const categoryId = matchedCategory?.id;
  const categoryName = matchedCategory?.name;

  const hasUserFilters = Object.keys(filters).length > 0;
  const hasPaginated = page > 1;

  const listSkusResult = useListSkus({
    page,
    limit: 20,
    category_id: categoryId ? [categoryId] : undefined,
    enabled: !hasUserFilters && hasPaginated,
  });

  const searchEnabled = hasUserFilters || filtersOpen;
  const filter = useMemo(() => buildFilter(filters, categoryName), [categoryName, filters]);

  const searchResult = useSearchProducts({
    query: "",
    page,
    limit: 20,
    facets: ["*"],
    filter: filter.length > 0 ? filter : undefined,
    enabled: searchEnabled,
  });

  const baseFacetsRef = useRef({
    distribution: {} as Record<string, Record<string, number>>,
    stats: {} as Record<string, { min: number; max: number }>,
  });

  const searchDistribution = searchResult.facetDistribution;
  const searchStats = searchResult.facetStats;

  useEffect(() => {
    const hasData = Object.keys(searchDistribution).length > 0;
    if (!hasUserFilters && hasData) {
      baseFacetsRef.current = {
        distribution: searchDistribution,
        stats: searchStats,
      };
    }
  }, [hasUserFilters, searchDistribution, searchStats]);

  const baseFacetDistribution =
    Object.keys(baseFacetsRef.current.distribution).length > 0
      ? baseFacetsRef.current.distribution
      : searchDistribution;
  const baseFacetStats =
    Object.keys(baseFacetsRef.current.stats).length > 0 ? baseFacetsRef.current.stats : searchStats;

  const useInitialData = !hasUserFilters && !hasPaginated;
  const skus = hasUserFilters
    ? searchResult.skus
    : useInitialData
      ? initialSkus
      : listSkusResult.skus;
  const pagination = hasUserFilters
    ? searchResult.pagination
    : useInitialData
      ? initialPagination
      : listSkusResult.pagination;
  const isLoading = hasUserFilters
    ? searchResult.isLoading
    : useInitialData
      ? false
      : listSkusResult.isLoading;
  const currency = skus[0]?.pricing?.currency ?? "INR";

  const handlePageChange = (newPage: number) => {
    setPage(newPage);
    window.scrollTo({ top: 0, behavior: "smooth" });
  };

  const handleFiltersChange = (newFilters: Record<string, unknown>) => {
    setFilters(newFilters);
    setPage(1);
  };

  const displayName = categoryName ?? "All products";

  return (
    <main>
      <PLPHero
        title={displayName}
        subtitle="Everything in this corner of the shop, no fluff — just the good stuff."
      />

      <div className="pt-8">
        <FilterSortBar
          filtersOpen={filtersOpen}
          setFiltersOpen={setFiltersOpen}
          itemCount={pagination?.total_records ?? skus.length}
          currency={currency}
          baseFacetDistribution={baseFacetDistribution}
          baseFacetStats={baseFacetStats}
          facetDistribution={searchResult.facetDistribution}
          filters={filters}
          onFiltersChange={handleFiltersChange}
        />

        <ProductGrid
          skus={skus}
          isLoading={isLoading}
          pagination={pagination}
          onPageChange={handlePageChange}
        />
      </div>
    </main>
  );
}

// apps/little-things-svelte/src/lib/components/category/CategoryContent.svelte
<script lang="ts">
import type {
  Item,
  Pagination as PaginationType,
  SearchProductsBody,
} from "@commercengine/storefront";
import { getSdk } from "$lib/storefront";
import FilterSortBar from "./FilterSortBar.svelte";
import PlpHero from "./PlpHero.svelte";
import ProductGrid from "./ProductGrid.svelte";

interface Props {
  displayName: string;
  categorySlug?: string | null;
  initialSkus?: Item[];
  initialPagination?: PaginationType;
}

let {
  displayName,
  categorySlug = null,
  initialSkus = [],
  initialPagination,
}: Props = $props();

let clientSkus = $state<Item[] | null>(null);
let clientPagination = $state<PaginationType | undefined>(undefined);
let clientFacetDistribution = $state<Record<string, Record<string, number>> | null>(null);

let isLoading = $state(false);
let filters = $state<Record<string, unknown>>({});
let page = $state(1);
let baseFacetDistribution = $state<Record<string, Record<string, number>>>({});
let baseFacetStats = $state<Record<string, { min: number; max: number }>>({});

const skus = $derived(clientSkus ?? initialSkus);
const pagination = $derived(clientPagination ?? initialPagination);
const facetDistribution = $derived(clientFacetDistribution ?? baseFacetDistribution);
const currency = $derived(skus[0]?.pricing?.currency ?? "INR");
const hasUserFilters = $derived(Object.keys(filters).length > 0);

function buildFilter(userFilters: Record<string, unknown>): (string | string[])[] {
  const conditions: (string | string[])[] = [];

  if (categorySlug) {
    conditions.push(`categories.slug = '${categorySlug}'`);
  }

  const priceRange = userFilters.price_range as { min: number; max: number } | undefined;
  if (priceRange) {
    conditions.push(`pricing.selling_price ${priceRange.min} TO ${priceRange.max}`);
  }

  for (const [key, values] of Object.entries(userFilters)) {
    if (key === "price_range") continue;
    if (!Array.isArray(values) || values.length === 0) continue;

    if (values.length === 1) {
      conditions.push(`${key} = '${values[0]}'`);
    } else {
      conditions.push(values.map((v: string) => `${key} = '${v}'`));
    }
  }

  return conditions;
}

let baseFacetsLoaded = false;

$effect(() => {
  if (baseFacetsLoaded) return;
  baseFacetsLoaded = true;

  const filter = buildFilter({});
  getSdk()
    .catalog.searchProducts({ query: "", page: 1, limit: 1, facets: ["*"], filter })
    .then(({ data }) => {
      if (data?.facet_distribution) {
        baseFacetDistribution = data.facet_distribution as Record<string, Record<string, number>>;
        if (clientFacetDistribution === null) {
          clientFacetDistribution = data.facet_distribution as Record<
            string,
            Record<string, number>
          >;
        }
      }
      if (data?.facet_stats) {
        baseFacetStats = data.facet_stats as Record<string, { min: number; max: number }>;
      }
    })
    .catch((e) => {
      // biome-ignore lint/suspicious/noConsole: surface facet load errors for debugging
      console.error("Failed to load base facets:", e);
    });
});

$effect(() => {
  const currentFilters = filters;
  const currentPage = page;
  const currentHasUserFilters = hasUserFilters;

  if (!currentHasUserFilters && currentPage === 1) {
    clientSkus = null;
    clientPagination = undefined;
    clientFacetDistribution = null;
    return;
  }

  const filter = buildFilter(currentFilters);
  isLoading = true;

  const body: SearchProductsBody = {
    query: "",
    page: currentPage,
    limit: 20,
    facets: ["*"],
    filter,
  };

  getSdk()
    .catalog.searchProducts(body)
    .then(({ data, error }) => {
      if (error) {
        // biome-ignore lint/suspicious/noConsole: surface search errors for debugging
        console.error("Search error:", error.message);
        return;
      }
      clientSkus = data?.skus ?? [];
      clientPagination = data?.pagination;
      if (data?.facet_distribution) {
        clientFacetDistribution = data.facet_distribution as Record<string, Record<string, number>>;
      }
    })
    .catch((e) => {
      // biome-ignore lint/suspicious/noConsole: surface search errors for debugging
      console.error("Failed to search products:", e);
    })
    .finally(() => {
      isLoading = false;
    });
});

function handlePageChange(newPage: number) {
  page = newPage;
  if (typeof window !== "undefined") {
    window.scrollTo({ top: 0, behavior: "smooth" });
  }
}

function handleFiltersChange(newFilters: Record<string, unknown>) {
  filters = newFilters;
  page = 1;
}
</script>

<PlpHero
	title={displayName}
	subtitle="Everything in this corner of the shop, no fluff — just the good stuff."
/>

<div class="pt-8">
	<FilterSortBar
		itemCount={pagination?.total_records ?? skus.length}
		{currency}
		{baseFacetDistribution}
		{baseFacetStats}
		{facetDistribution}
		{filters}
		onfilterschange={handleFiltersChange}
	/>

	<ProductGrid {skus} {isLoading} {pagination} onpagechange={handlePageChange} />
</div>
